version: '3.5'

services:
  postgres:
    container_name: PostGres
    image: postgres
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@nest.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres: